## Condicionalidade

**Definição**. Para dois eventos quaisquer $A$ e $B$, sendo $P(B) > 0$, definimos a *probabilidade condicional* de $A$ dado $B$, denotada por $P(A|B)$, como sendo

\[
P(A|B) = \frac{P(A\cap B)}{P(B)}.
\]

## Independência 

Da definição de probabilidade condicional, temos que

\[
P(A \cap B) = P(A|B)P(B).
\]

Se a ocorrência de um evento $B$ não trouxer nenhuma informação sobre a ocorrência ou não de um evento $A$, dizemos que $A$ e $B$ são independentes.

Formalmente, dizemos que dois eventos quaisquer são independentes se

\[
P(A \cap B) = P(A)P(B).
\]

## Teorema de Bayes

O Teorema de Bayes é dado pela seguinte expressão:

\[
P(A|B) = \frac{P(B|A)P(A)}{P(B)}.
\]

### Resultado

Seja $A$ um evento de $\Omega$ e $C_1, ..., C_n$ uma partição desse espaço amostral. Então

\[
P(A) = \sum_{i=1}^{n} P(A|C_i)P(C_i)
\]

Pelo resultado, podemos escrever o Teorema de Bayes como

\[
P(C_i|A) = \frac{P(A|C_i)P(C_i)}{\sum_{i=1}^{n} P(A|C_i)P(C_i)}.
\]

### Exemplo

Em uma fábrica de parafusos, as máquinas $A$, $B$ e $C$ produzem 25%, 35% e 40% do total, respectivamente. Da produção de cada máquina 5%, 4% e 2%, respectivamente, são parafusos defeituosos. Escolhe-se ao acaso um parafuso e verifica-se que é defeituoso. Qual a probabilidade de que o parafuso venha da máquina $A$?

Vamos definir os seguintes eventos:

$A$: o parafuso foi produzido pela máquina $A$

$B$: o parafuso foi produzido pela máquina $B$

$C$: o parafuso foi produzido pela máquina $C$

$D$: o parafuso é defeituoso

Pelo enunciado, sabemos que: $P(A) = 0.25$, $P(B) = 0.35$, $P(C) = 0.40$, $P(D|A) = 0.05$, $P(D|B) = 0.04$ e $P(D|C) = 0.02$. Dessa forma,

\[
P(A|D) = \frac{P(D|A)P(A)}{P(D)} = \frac{P(D|A)P(A)}{P(D|A)P(A) + P(D|B)P(B) + P(D|C)P(C)} = 
\]
\[
= \frac{0.05\cdot 0.25}{0.05\cdot0.25 + 0.04\cdot0.35 + 0.02\cdot0.40} = 0.3623 = 36,23\%.
\]
